### ISSUE TITLE
缺少boost

### ISSUE THREAD

**Issue by Lichangch** [Readon/msys2-installer#1]
仿真工具切换为iverilog后，提示缺少boost
<img width="677" alt="微信图片_20240629134817" src="https://github.com/Readon/msys2-installer/assets/103412962/55f167d6-5aef-4e48-96ef-40e2cfd1daef">
<img width="459" alt="微信图片_20240629134823" src="https://github.com/Readon/msys2-installer/assets/103412962/57894206-b7e7-4a57-9bc0-b6badf35b168">

**Comment by Readon** [comment]
8650ce48ca8469ae7f6caa94a790e075ff99dac6 should fix this
